### ISSUE TITLE
zope.file is not on GitHub; can it be migrated?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.html#1]
zope.file is a dependency of this project, but it's not hosted on GitHub. zope.file is aging and in need of some attention for newer versions of Python. I'd be happy to work on that if someone can help with the migration. (Or if there's no history, I'm happy to import the current state of the code as it exists on PyPI.)

cc @mgedmin and @tseaver 

Thanks in advance.

**Comment by icemac** [comment]
@jimfulton has the backup of svn.zope.org. He should be able to a GitHub repository.

**Comment by jimfulton** [comment]
Yup, will do.

**Comment by jimfulton** [comment]
Done.

Thanks @jamadden !

**Comment by jamadden** [comment]
Thanks @jimfulton !
