### ISSUE TITLE
Is this package still needed/used?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.html#2]
It does not claim to support Python 3 and tests are broken (see [TravisCI](https://travis-ci.org/zopefoundation/zope.html/builds/443426148)).

I propose to archive this repository.

Anyone to veto against this proposal?

**Comment by jamadden** [comment]
I couldn't find any uses of it here, and our large zope-3-ish application doesn't pull it in. Back in 2010 [it was declared](https://github.com/zopefoundation/zopetoolkit/blob/4bfaae448af17330332c5d6797eb0e727a42d461/docs/attic/releaseteam/meeting-20100615.rst) "not fundamental".

**Comment by mgedmin** [comment]
As long as https://pypi.org/project/zope.html/ exists I don't think we should remove git repositories.

We might change trove classifiers to indicate that it's deprecated/unmaintained and disable Travis.

**Comment by tseaver** [comment]
Summoning @menesis, @satchit, @benji-york, @baijum, @thefunny42, @jamur2, @strichter, @jinty, and @freddrake, each of whom has left fingerprints here.

I favor @mgedmin's suggestion:  leave the repository, disable Travis, and update the classifier.

**Comment by icemac** [comment]
@tseaver Your suggestion looks okay to me. My original proposal was to archive the repository as described in https://help.github.com/articles/archiving-a-github-repository/. I propose to additionally do it. See zopefoundation/zmi.styles as an example of an archived repository. (There is no need to delete all the code as done in that repository.)

**Comment by mgedmin** [comment]
It's probably fine for zope.html, but how will we discover if there are users of this package if we make the issue tracker read-only?  AFAIU regular committers can't unarchive a repo, you need an admin to do that.

**Comment by icemac** [comment]
@mgedmin Okay, you won. 🥇

**Comment by thefunny42** [comment]
I do not use this package, and I like the idea of archiving it, it will still be accessible. If you leave the repository around, please update the ``README.txt`` of the package to say that is no longer maintained and that there will no be any other release, that will prevent people to false expectations.

We should definitely not delete it.
